/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.accountkit;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.facebook.accountkit.AccessToken;
import com.facebook.accountkit.AccountKit;
import com.facebook.accountkit.AccountKitError;
import com.facebook.accountkit.AccountKitLoginResult;
import com.facebook.accountkit.ui.AccountKitActivity;
import com.facebook.accountkit.ui.AccountKitConfiguration;
import com.facebook.accountkit.ui.ButtonType;
import com.facebook.accountkit.ui.LoginType;
import com.facebook.accountkit.ui.TextPosition;

@Kroll.module(name="TiAccountkit", id="ti.accountkit")
public class TiAccountkitModule extends KrollModule
{
	private static final String LCAT = "TiAccountkitModule";
	private static final boolean DBG = TiConfig.LOGD;

    @Kroll.constant public static final String RESPONSE_TYPE_AUTHORIZATION_CODE = AccountKitActivity.ResponseType.CODE;
    @Kroll.constant public static final String RESPONSE_TYPE_ACCESS_TOKEN = AccountKitActivity.ResponseType.TOKEN;

	public TiAccountkitModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		// put module init code that needs to run when the application is created
	}
    
    // Methods
    @Kroll.method
    public void initialize(String responseType)
    {
        // TODO: Implement method
    }
    
    @Kroll.method
    public void loginWithPhone(@Kroll.argument(optional = true) String phone)
    {
        // TODO: Implement method
    }
    
    @Kroll.method
    public void loginWithEmail(@Kroll.argument(optional = true) String email)
    {
        // TODO: Implement method
    }
}

